# Generated by Django 5.2.4 on 2025-08-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_contributor_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='author',
        ),
    ]
